### ISSUE TITLE
Add TextEncoder polyfill to the SDK

### ISSUE THREAD

**Issue by thivi** [asgardeo/asgardeo-auth-js-sdk#113]
**Describe the issue:**
One of the dependencies of this SDK uses the `TextEncoder` API. Since this is not supported in React Native, this polyfill has to be manually installed. It will be better for the developers if the polyfill can be packaged by the SDK itself.

**Comment by jay-jlm** [comment]
@thivi 
Hi, this looks like it's  an old issue, is it still relevant after all the refactoring that has occurred since then?

**Comment by thivi** [comment]
Hi @jay-jlm,
This is no more relevant as this code segment has been moved out of the SDK by https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/167
