### ISSUE TITLE
Status of the repository

### ISSUE THREAD

**Issue by slavafomin** [asgardeo/asgardeo-auth-js-sdk#121]
Hello!

I was looking for JavaScript library to work with the WSO2 Identity Server and found this very promising solution. I can see that it's made by some people who are also members of official WSO2 organization, but I can't figure out what "Asgardeo" is and why this library is not published at the official WSO2 repository. Also, the WSO2 itself is almost not mentioned in the library's README.

Could you please clarify this for me (the relations between WSO2 and something which is called Asgardeo)? It would be even better to update the documentation to clarify this as well.

Thank you!

**Comment by ayshsandu** [comment]
Hi @slavafomin ,

SDKs developed by the WSO2 IAM team is called `Asgardeo` SDKs, named referring to something exciting that the WSO2 team is working on. 

These SDKs are not coupled to the WSO2 Identity Server and the community can use them to integrate application authentication with any Identity provider which supports standard authentication protocols.

And `asgardeo` repositories are owned and maintained by the WSO2 team and has only community support as of now.
